### ISSUE TITLE
Vue wrapper bug (again)

### ISSUE THREAD

**Issue by leontepe** [arnog/vue-mathlive#15] opened 2020-05-24 18:50 UTC
I can't help but recreate this issue, because it is still not resolved for me and I have the feeling that something is going wrong. The problem is the same as in #14 basically, but now I have removed the intermediate component and I am using a list that I am reading from and writing to local storage and using `v-for` to render the list.

Here, once again, using the `<input>` component, it works fine, even when just using `v-model` instead of the more verbose version with `v-bind:value="..."` and `v-on:input="$emit('input', $event.target.value)"` and it works without any Vue errors or warnings in the console since I am not messing around with components directly this time.

This doesn't work for the `<mathfield-mathlive>` component though. Even if I exchange it with the verbose version and use `v-on:input="$emit('input', $event)"`, as you pointed out in your last response. When the site loads, the values don't show up. It seems like the values _are_ getting overwritten once I change them though. The initial values that are loaded from local storage just don't show up for some reason.

Also, I don't understand why this happens only with lists, since it works fine for an example with just one <mathlive-mathfield> tag and just one `formula` value.

This time I created JSFiddles so you can quickly see what I am talking about:

1. [JSFiddle using `v-model`](https://jsfiddle.net/leontepe/sa4qyzbe/83/)
2. [JSFiddle using verbose version](https://jsfiddle.net/leontepe/tzp6f4wg/11/)

I really don't know at this point whether I am just making some stupid mistakes all the time or whether there is actually something wrong here, but I can't figure it out.

**Comment by arnog** [comment] 2020-05-24 19:49
I don't see the values load, but I get this in the console:
> Vue warn: Error in mounted hook: "SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document."

Thanks for the JSFiddle, they're very useful, but could you include some step-by-step that I could follow to try to reproduce the problem?

**Comment by leontepe** [comment] 2020-05-24 20:10
@arnog Hm, that doesn't happen for me. Just did a quick google search of the error and maybe you have disabled third-party cookies in your browser?

**Comment by arnog** [comment] 2020-05-24 22:32
Ah, indeed, that was the problem.

You need to set the value of the mathfield for it to be restored when you create it, that is, change:
```html
<li v-for="formulaObj in formulaList">
<mathlive-mathfield v-model="formulaObj.value"></mathlive-mathfield>
</li>
```
to
```html
<li v-for="formulaObj in formulaList">
<mathlive-mathfield v-model="formulaObj.value">{{ formulaObj.value }}</mathlive-mathfield>
</li>
```

**Comment by leontepe** [comment] 2020-05-24 23:09
@arnog, hmm but isn't this a non-Vue way to do it? Shouldn't `v-model` mean that the component automatically updates, even without the placeholder inside? Is it even possible to change this? 🤔

**Comment by arnog** [comment] 2020-05-25 01:42
Dunno. Seems to be the way Vue works. Apparently you're not the first one tripped up by this: https://github.com/vuejs/vue/issues/8893

**Comment by arnog** [comment] 2020-09-30 07:30
Closing, as this seems to be a Vue issue, and it does seem to be a design choice from Vue.

**Closed by arnog** 2020-09-30 07:30 UTC
