### ISSUE TITLE
Unable to find the fontsDirectory

### ISSUE THREAD

**Issue by TCMAD** [arnog/vue-mathlive#30] opened 2020-11-21 10:41 UTC
Hi I try to render my formulas but I get errors on console that says:
![image](https://user-images.githubusercontent.com/40864981/99874182-ef772480-2be5-11eb-90b9-f5072a4a1c76.png)

The files are present on my node_module
![image](https://user-images.githubusercontent.com/40864981/99874375-c3f53980-2be7-11eb-8066-5587d60ef841.png)

I tried to resolve this by adding on HTML tag `:options={fontsDirectory='/src/node_modules/mathlive/dist/fonts'` and testing multiples paths but no change.

The funny part is when I compare the original mathfield and the vue mathfield, the original works perfectly but I need to extract the data with `v-model`. The vueField is present and I can enter content but it will not render. 
![image](https://user-images.githubusercontent.com/40864981/99874826-f05e8500-2bea-11eb-8f2d-e22e547ed749.png)
![image](https://user-images.githubusercontent.com/40864981/99874844-1edc6000-2beb-11eb-98a3-1f5820149e3e.png)

Here is my code:
```vue
<template>
   <div>
            <label for="question">Mathfield (Original)</label>
            <math-field
              virtual-keyboard-mode="manual"
              v-bind:value="question"
              v-on:input="question = $event"
            ></math-field>
            <p>Résulat : {{question}}</p>
   </div>
   <div>
            <label for="question">Mathlive-Mathfield (Vue version) not render</label>
            <mathlive-mathfield
              :options="{smartFence:false, fontsDirectory:'./fonts'}"
              v-model="question"
            ></mathlive-mathfield>
            <p>Résulat : {{question}}</p>
    </div>
</template>

<script type="module">
import Vue from 'vue'
import MathLive from 'mathlive/dist/mathlive.min.js'
import Mathfield from 'mathlive/dist/vue-mathlive.mjs'

Vue.use(Mathfield, MathLive)

export default {
  name: 'MathLive_Test',
  data: function() {
    return {
      question: null
    }
  }
}
</script>
```
You told me on [#695](https://github.com/arnog/mathlive/issues/695) to check the fonts binds with firefox but I have the same errors on different browsers.

I think #23 refer to this errors too.

**Comment by arnog** [comment] 2020-11-21 16:04
I would really like to help you but there just isn't enough information in the bug report for me to do that. I would need to have access to your code, either as a GitHub project or a CodePen in order to debug it.

The "rejected by sanitizer"error is produced by FireFox. If you see the same error in other browsers, I have no idea how that happens.

Have you checked that the font file was actually reachable? Does the URL "http://localhost:8080/js/fonts/KaTeX_Fraktur-Regular.woff" appear in your Network tab? If you paste this URL in the browser, does the fontfile get downloaded?

Is your server configured to accept WOFF (and WOFF2) files. (i.e. return the proper MIME types)

**Comment by TCMAD** [comment] 2020-11-22 18:32
I tried to download by the URL but nothing. I will check on my server config.

**Comment by TCMAD** [comment] 2020-11-25 21:13
Hello, 

I did a sandbox with a basic example with Vue-mathlive . Just click [here](https://codesandbox.io/s/mathlive-test-mlvs7)

And unfortunately the Vue Mathfield not render.

**Comment by arnog** [comment] 2020-11-26 10:50
Thanks for this sandbox, that was very useful.

(Unrelated to this problem, but you should use `v-on:input="formula = $event.target.value"` to read the value of the formula)
 
Also not directly related, but the property to specify a custom directory for the fonts is `fontsDirectory`, not `fonts`. It's not directly related because the default value actually works (the fonts you use are stored in the `node_modules/mathlive/fonts` directory, and this directory is already adjacent to the `mathlive.min.js` library. So, you can safely remove the `fonts` option.

The problem is an interaction between codesandbox and FireFox. Firefox does some "font sanitizing"/validation and it appears that codesanbox is not properly setup to send 'woff'/'woff2' fonts in a way that Firefox accepts. This triggers an error (the `downloadable font: rejected by sanitizer` messages displayed in the console), and as a result the fonts are marked as "not loaded". This, in turns, result in the content of the mathfield appearing to be blank (although the content is not displayed, the mathfield is live and you can interact with it). In fact, despite Firefox complaints, the fonts *are* loaded. I have changed Mathlive to now assume that the font *might* be loaded, even if an error is received.

Why did the `<math-field>` display correctly? It displays correctly because to prevent the fonts from displaying when they are not loaded relies on a CSS selector set on the body of the document. This selector is not applicable when inside the dark shadow root of a custom element.

Your workarounds include:
- using a browser other than Firefox
- requesting that codesandbox serves woff and woff2 fonts to Firefox liking (they probably just need to add a MIMEType to their server configuration)
- using `<math-field>` instead of `<mathlive-mathfield>` (is there any reason you would need `<mathlive-mathfield>?)
- updating to a future version of MathLive that will include the workaround to display fonts even if they appear to have failed to load

**Closed by arnog** 2020-11-26 10:50 UTC

**Comment by TCMAD** [comment] 2020-11-28 08:14
Thanks for your comments, it really helps me to understand and unlock my project!

I used the `<mathlive-mathfield>` because I thought it was the only way to use the `v-model` property on Vue.
I followed the ReadMe and did research on cortexjs.io but it wasn't enough.

And like I mentioned before, I tested the field also on chromium-browser. And I've found a similar issue:

![image](https://user-images.githubusercontent.com/40864981/100497059-3e2e3c80-3159-11eb-8388-f797ca50f315.png)
